services:
  humble:
    build:
      context: .
    stdin_open: true
    tty: true
    network_mode: "host"
    ipc: "host"
    volumes:
      - ./:/workspace
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
    command: /bin/bash